### ISSUE TITLE
Meteor-build-client

### ISSUE THREAD

**Issue by frozeman** [chicagogrooves/mini-meteor#2]
I think you would be interested in my npm package https://www.npmjs.com/package/meteor-build-client

Could you add examples on how to use you script? I can't see the linked source file anywhere in your examples code.

I'm actually looking for a minimongo for node.js

**Comment by deanrad** [comment]
I've kinda let this project get stale :/ - have you seen asteroid.js ? https://github.com/mondora/asteroid - not sure what it includes but it's more complete than mine, which just ships Tracker and its dependencies.

**Comment by frozeman** [comment]
The whole point for me is to use meteor in the frontend, because i think blaze is one of the best template engines out there.

Would you link to my `meteor-build-client` in you're readme? I think it will help a lot of people, coming across yours.
